### PR TITLE
Changes to lines - 38, 41

### PR DESCRIPTION
**Pull request by nicksta16**
Made changes needed for lines 38 and 41

### CODE REVIEW

**Comment by TheMagicFlute** [comment]
> Made changes needed for lines 38 and 41

Good. Please wait for him to merge this PR.

**Comment by TheMagicFlute** [comment]
#2

**Comment by TheMagicFlute** [comment]
@nicksta16 Thanks for Your PR

**Comment by FriendlyXuKun** [comment]
The modification has been completed. And thank you for your suggestion.

**Pull request closed without merging**
